### ISSUE TITLE
Migrate tests to Node.js test runner

### ISSUE THREAD

**Issue by coderbyheart** [MLopezJ/asset-tracker-lwm2m-js#17]
Replace jest with the [Node.js test runner](https://nodejs.org/api/test.html) (and [tsmatchers](https://github.com/SimoneGianni/tsMatchers) for assertions if needed).

**Comment by MLopezJ** [comment]
- [x] Check that all test uses `node test runner`
- [x] update package JSON, removing the `jest` attribute from there.  https://github.com/MLopezJ/asset-tracker-lwm2m-js/commit/0530de2c9d4c73d8c9f89c33226a8dbb695d9656
- [x] TsMatcher is not used. So far the assertions have been performed with the [node:assert](https://nodejs.org/api/assert.html#assert) module and it works as expected.

**Comment by coderbyheart** [comment]
Thanks!
